### PR TITLE
API keys & submissions 

### PR DESCRIPTION
**Pull request by iiacoban42**
Added the login to submission + unit test.

Played with API keys a bit, they are quite practical for autonomous submissions, as a login alternative, however they have to managed similarly to a password. So, unfortunately, we can't enforce how they're managed at the other end of the connection. https://florimondmanca.github.io/djangorestframework-api-key/security/#caveats

From a security stand point API key and login are quite similar, in both cases key/password leaks could lead to compromised accounts. We could use API keys as follows: the key is showed to the user just once and afterwards the key can only be reset (Twitter does it like this). If lost it can never be recovered. It's less of hassle to change than a password and it would be stronger than a user made up password. When looking at it this way API keys come on top of the login.

### CODE REVIEW

**Comment by StefanoSperetta** [comment]
What if we use a much more simplified mechanism for the API keys, basically allowing max 1 API key to be used (which also means that by regenerating it we automatically revoke the previous one)? My idea would be to simply add a column in the users' schema called API key and query the users' database for username and API key when submitting. If a line is found, then the user is registered and using a legitimate API key.

This API key we could simply generate automatically in the user registration function (for the moment, and then later adding a button in the profile page). This could be very simple to implement and it would completely decouple the data submission and the website login.

**Comment by iiacoban42** [comment]
Indeed this is a good option too, we'll need to store the keys in the same manner as passwords though, but that's no problem. The django framework variant does have support for managing the keys in django admin, which sounds nice to have. It's probably not complicated to incorporate, just need to figure out exactly how. I can give it another go in 2 weeks time, if it's not urgent.

**Comment by StefanoSperetta** [comment]
Look very cool! I will deploy it tomorrow on the virtual server and give it a try.

**Comment by iiacoban42** [comment]
Great! Let me know if I should add anything to it. Maybe a default expiration date would be desirable? Could add that in no time.

**Comment by StefanoSperetta** [comment]
I have been trying to deploy it on the virtual server but I consistently have issues with the proxy (nginx keeps returning error 400, bad request). If I cherry-pick the latest commits from main then it starts working again. I think this will be fixed in the merge process so I am not going to look into it any further.

I made a simple python script that submits a POST request and I got it to work fine after some fiddling. The main problems:
- CSRF cookie validation: I had to disable it with a decorator on the view function otherwise it always fails. In principle, I do not think this is a security issue as we use the API key but I am not so sure...
- some more error handling would be needed as it took a while to get it right (I submitted initially the frame as text and not as JSON and spent quite a while debugging the problem.. maybe some better responses to be added).

I will push today or tomorrow my fixes in this branch (including some error handling) so we can merge it in main. Overall, key management was quite simple and I like the fact the key is displayed only once. We might improve the HTML a bit (like adding a "Copy to Clipboard" button as the key sometimes gets characters that break the "double-click-to-select" only selecting a part of the key.

I like also the Django Admin page, it is quite handy. But I see two "API keys" items in the index but the top one seems not to find any key, while the second works great.

image

**Comment by iiacoban42** [comment]
I updated this branch with the latest commits on main, so hopefully nginx won't complain now. I think I found another problem related to permission classes. If a custom API keys model is used, then a custom permission class has to be created, so this means that `@permission_classes()` annotation for `submit_frame` is not doing anything. That could be why the first API keys table is empty, but I'm guessing here, still debugging this one... Disabling CSRF validation is okay as long as we don't use cookies. I do agree about the error handling, it can definitely be improved.

**Comment by StefanoSperetta** [comment]
Disabled CSRF cookie for REST API, this allows an external application (python script using requests) to submit.
Also added the submitter user agent string to the database and added some more fine-grained error handling.

**Comment by iiacoban42** [comment]
Is CSRF cookie validation still in place for the user login? It should be there for that one.

**Comment by StefanoSperetta** [comment]
yes, the cookie has been disabled only for the submit_frame url

**Comment by iiacoban42** [comment]
Yep, that's alright

**Comment by StefanoSperetta** [comment]
I am currently using this script to inject frames:  
```
import requests
import json

frame = '{ "qos": 98.6, "pass": "qwerty", "frequency": 2455.66, "frame": "A8989A40404000888C9C66B0A80003F0890FFDAD776500001E601983C008C39C10D02911E2F0FF71230DECE70032044C09500311119B8CA092A08B5E85919492938285939C7900000000000000000000005602F637005601F3380000006D70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000434B1345B440BF3C9736D0301D240E000004B82C4050B26DDB942EB4D0CFE4E9D64946"}'
frame_json = json.loads(frame)

# defining the api-endpoint
endpoint = "https://delfitlm.tudelft.nl/submit_frame/"

# your API key here
API_KEY = "your-API-key-here"

use_header = {"HTTP_AUTHORIZATION": API_KEY}
rpacket = requests.post(url=endpoint, json=frame_json, headers={'Authorization': API_KEY, "User-Agent": "test_submit v 0.0"}, timeout=10)
print(rpacket)
print(rpacket.text)
```

**Comment by iiacoban42** [comment]
Looks good! We could put it on the website.

**Comment by StefanoSperetta** [comment]
Thanks, I was struggling with fixing the date times!

**Review by StefanoSperetta — APPROVED** [review]
I am happy to merge this in main, the API key works fine.

I will add another issue with respect to improving unit testing of the frame submission and solving some warnings on the timezone. But I think the work on the API key is done.

**Pull request merged**
