### PR TITLE
59 update db schema

### LINKED ISSUE #59: Update db schema
1.  Add a new stand-alone table for TLE with the following fields :

- valid_from (date time field)
- valid_until (date time field)
- sat (char)
- tle (text field)

2. Add a location field to the members table. 

- for this one we could use `PointField` for coordinates: code snippet [here](https://stackoverflow.com/questions/11421230/django-how-do-i-store-a-geo-point-in-database), docs [here](https://docs.djangoproject.com/en/4.0/ref/contrib/gis/geos/#django.contrib.gis.geos.Point) 
- or text field for maidenhead locator system

### PR DESCRIPTION
**Pull request by iiacoban42**
Added a table for TLEs (and website view) as well as a location field in the members table with maidenhead system in mind. 

Should we make location required info at sign-up?  Also should updating the location be possible? And if so, shall we keep history of past locations? Then, I think we'll an extra table for user locations.

Closes #59

### CODE REVIEW

**Comment by StefanoSperetta** [comment]
I would make it easy for us and simply add a fixed location in the user table. I would simply add Latitude and Longitude such that a user can add GPS coordinates.

**Comment by StefanoSperetta** [comment]
I think we can keep the TLE overview table but I would remove the _valid_until_ field and the filter. Such value does not really exist for a TLE.

The choice of placing the TLE in the ewigs app is a bit unexpected but it makes sense. What we should keep in mind is that the ground station will track multiple satellites so we will have TLEs from many satellites in this table. This means the _sat_ field should probably be a select, not a text box.

The _valid_from_ field should be automatically generated from the TLE itself otherwise I think we will have a lot of potential problems. As mentioned in the issue, we might add a custom Admin page (basically downloading the HTML of the standard admin page and removing the _valid_from_ field to have that one populated once we save by processing the TLE. There are also javascript libraries to process (and check) TLEs but they seem to all require node.js so maybe I would skip those.

Parsing the validity date from the TLE can also be done without a full TLE library (like SkyField) as the TLE uses a fixed position encoding and you only need to cut certain characters from the first line and do some math with a datetime object (year plus days from Jan 1st plus fractional part of the day). A full library would allow us to also perform TLE validation.

**Comment by iiacoban42** [comment]
I did use SkyField for getting the validity date and valid_until is removed. We could add the validity date to the table as we add a new TLE to the table, that's how it works now. I could also make an admin action for processing the dates https://docs.djangoproject.com/en/4.0/ref/contrib/admin/actions/, but if we can process it from start it might not be necessary to do it manually in Admin.

**Comment by StefanoSperetta** [comment]
I am not sure I follow what you mean with "if we can process it from start". What we might simply do is have the admin page show only the satellite name and the text field for the TLE and set the validity date field as non-editable (https://books.agiliq.com/projects/django-admin-cookbook/en/latest/uneditable_field.html). 

Then, we need a validation function to check if the TLE is valid and then add the validity date in the database (https://stackoverflow.com/questions/24802244/custom-validation-in-django-admin).

**Comment by iiacoban42** [comment]
What I'm proposing is that we add the validity date right when we add a new TLE, not later. We extract the date from the TLE epoch and add them both (TLE and date), as we poll for new TLEs in a server process. Then you don't need to take any action via django admin or at least I don't see why. If you want to be able to add a TLE via the admin page, then we might need an admin action to update the entry with the validity date, though I find the server process approach to be much simpler.

**Comment by StefanoSperetta** [comment]
The process can then be used only after NORAD has recognized the object. For Delfi-PQ, this happened about 3 weeks after launch but there are still 6 objects from our launch that do not have a Norad ID now. 

Adding manual TLEs is really needed for the first 3-4 weeks of operations but we can skip it for now (as Delfi-PQ is done with this).

**Review by StefanoSperetta — APPROVED** [review]
I think at this stage we can merge this in main as it contains the basic TLE storage functionality and it adds the user position.

Further TLE work (the auto-download) requires extra work and I do not think we really need it for this PR (which is basically about the schema update).

**Comment by iiacoban42** [comment]
Alright understood, sorry for the confusion. I'll look into what options we have with Admin.

**Pull request merged**
