### PR TITLE
49 add email sending support

### PR DESCRIPTION
**Pull request by StefanoSperetta**
Adding basic email sending capabilities. This branch is based on #45 and it adds a very basic email being sent after the user successfully registers. The email text should probably be improved (together with basic email verification, as in #28) but this branch can act as a starting point.

This branch requires an external unencrypted SMTP server to send emails: this branch has been deployed on the telemetry virtual server and sends emails successfully upon new user registration). SMTP server configuration is done via an external env file containing the private email server details.

### CODE REVIEW

**Review by iiacoban42 — APPROVED** [review]
Looks good! We could use `EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'` for development. It prints the emails that get sent to the console like this. 

```
[06/Jan/2022 20:41:03] "GET /members/register/ HTTP/1.1" 200 1747
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: Welcome to the DelfiTLM portal!
From: webmaster@localhost
To: space_enthusiast@mail.com
Date: Thu, 06 Jan 2022 20:42:25 -0000
Message-ID: <164150174514.169099.13623449331023164741@pop-os.localdomain>

Dear space_enthusiast,
 thank you for joining the DelfiTLM portal: with this portal, you can submit telemetry for all the DelfiSpace satellites. 
-------------------------------------------------------------------------------
[06/Jan/2022 20:42:25] "POST /members/register/ HTTP/1.1" 200 436
```
Quite useful!

**Comment by StefanoSperetta** [comment]
Would it be an option to check the SMTP_HOST environmental variable, if empty, we switch to the console backend, otherwise, we use the smtp backend?

**Comment by StefanoSperetta** [comment]
Other point: I am really not sure putting the email text in there is a great idea (especially for ease of configuration) but I have no clue how to deal with it otherwise so for now I would leave it as is, waiting for a better idea... Is there maybe a way to put a configuration field changeable from Django Admin?

**Comment by iiacoban42** [comment]
Now the emails are printed when there no SMTP host defined. We could have some functions that generate the email text, or store the text in some txt files. Django admin can manipulate the models, so to be able to use that the emails should be defined as a model or stored in the db somehow.

**Comment by iiacoban42** [comment]
Just discovered admin actions https://stackoverflow.com/questions/18619577/using-django-admin-actions-to-send-bulk-emails/41885626. We could use this to send non-automatic emails and define some builder functions for auto-emails like the registration text.

**Comment by StefanoSperetta** [comment]
Nice! I tested it on the server and it looks good.

**Pull request merged**
