### PR TITLE
Security improvements

### PR DESCRIPTION
**Pull request by StefanoSperetta**
Improve security in the application
- [x] removing spurious key in docker.compose-deploy.yml
- [x] switch to newest version of crowdsec-firewall-bouncer-iptables
- [x] document installation / configuration of the newest version of crowdsec-firewall-bouncer-iptables
- [x] add extra crowdsec scenarios:
  - https://app.crowdsec.net/hub/author/crowdsecurity/collections/http-cve
  - https://app.crowdsec.net/hub/author/crowdsecurity/collections/base-http-scenarios
  - https://app.crowdsec.net/hub/author/crowdsecurity/collections/whitelist-good-actors
- [x] add whitelist options (for legit IP scanners)
- [x] implement Django axes to protect against brute-forcing (https://dev.to/arnopretorius/manage-failed-login-attempts-with-django-35pj)
- [x] implement session cookie expire rules
- [x] add dependabot.yml to scan dependencies on dockerfile* and requirements.txt

### CODE REVIEW

**Comment by StefanoSperetta** [comment]
Added Django Axes and maximum number of unsuccessful login attempts set to 6. This works nicely but the error message should be improved as it ignores the page layout and creates an empty page only with the error message

**Comment by StefanoSperetta** [comment]
Django Axes by default only matches IP so if a user logs in with multiple users from one ip, each succesfull login will unblock all users from that ip.

https://django-axes.readthedocs.io/en/latest/5_customization.html#customizing-lockout-parameters

**Comment by StefanoSperetta** [comment]
Logging username and IP address might lead to GDPR issues: https://django-axes.readthedocs.io/en/latest/3_usage.html#data-privacy-and-gdpr

**Comment by StefanoSperetta** [comment]
The crowdsec configuration directory is available in the mounted volume delfitlm_crowdsec_config at the path /var/lib/docker/volumes/delfitlm_crowdsec_config/_data/parsers/s02-enrich/whitelists.yml

The path is a symlink so it needs to be deleted and a new file created and edited.

Documentation to be added before closing the PR.

**Comment by StefanoSperetta** [comment]
Development completed but some extra features are required: unit tests for the Axes login (and account locking in case of wrong password) is still to be implemented in a separate branch.

**Review by iiacoban42 — APPROVED** [review]

**Pull request merged**
