### PR TITLE
13 docker image

### PR DESCRIPTION
**Pull request by iiacoban42**
- Added docker images for the deployment. 
- Had to change the folder structure and pylint config to make it work. 
- Docker will run a server and an nginx proxy. The proxy servers static files more efficiently and it's considered good practice for scalability, so it's there.
- Currently, it run with HTTP, to make it HTTPS we need to use `--https` flag in `entrypoint.sh`. This is an example form uwsgi documentation: `uwsgi --master --https 0.0.0.0:8000,foobar.crt,foobar.key`

### CODE REVIEW

**Comment by StefanoSperetta** [comment]
I took a little bit of fiddling but I got the webserver to work on my MAC!

Why do you have 2 separate docker compose files (docker-compole.yml and docker-compose-deploy.yml)? If I build the first one I get an error due to the missing sqlite (_docker logs delfitlm_app_1_):

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 209, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

Where is the database? Shouldn't there be a separate database container in the virtual network? Especially because you will need to create a persistent folder for the database files.

But if I build the docker-compose-deploy.yml file, I get the working webserver and Django instance.

Overall, I like the reverse proxy, it works great in a production environment and it gives you a lot of flexibility (we might even think about stuff like fail2ban in the future)

I would ignore the GitGuardian warning, it's quite obvious we will use another non-public secret once in full production

I see you are rebuilding the nginx image (great choice, I am an apache dinosaur and never ventured past that). In practice if you change the configuration files often this takes a lot of time as you have to rebuild the image. It might be simpler to use the default nginx and mount the via volumes the default.conf and uwsgi_params files so you can change them on the fly (besides a nginx restart).

You might have to think about an extra catch-all page for errors (future thing)
image

Overall, a couple of questions but it looks good to me!

**Comment by StefanoSperetta** [comment]
Sorry, wrong button pressed ;-)

**Comment by StefanoSperetta** [comment]
I think I understand now why you have 2 separate docker-compose files, based on your comments in the README.md!
I did not see the notes in the file and run the default docker-compose file without running the local instance.

I would update the readme file as you could start everything by simply running the last command (item 7, for deployment) but the first commands are needed to build the development environment, I guess. 

Anyway, the deploy compose image works fine, go ahead and merge!

**Comment by iiacoban42** [comment]
Sorry about the database trouble.. if you add an empty `db.sqlite3` file in `delfitlm` folder it should work, it's just a dummy right now. I see now that it's in the gitignore and didn't reach github. 

As for the two docker images, the difference between them is that the deploy one is used for proper deployment, while the other simulates a deployment with django debug mode enabled. Debug mode is very useful and we'll use that image for development. They also run on different ports, 80 and 8000 respectively.

Debug mode off (production) will show a page like this for unavailable urls:
image


While debug mode on will provide logs and other useful info:
image

Actually I realized that both were running with debug=true but it's fixed now :)

**Pull request merged**
