### PR TITLE
66-naive-datetime

### PR DESCRIPTION
**Pull request by StefanoSperetta**
These changes should address the warning on the use of a naive time format. 

The timefield written into the database has been verified manually by using pgadmin and the values are:
- 2019-12-24T14:39:29.139Z (Value set in the POST request in JSON)
- 2019-12-24 14:39:29.139+00 (Value retrieved from the database)

A proper unit test is also coming up...

### CODE REVIEW

**Comment by StefanoSperetta** [comment]
I added only a basic unit test to verify the data written in the Downlink object are consistent (my main worry was the mishandling of the timezone). This class misses probably some more unit tests but I would address that in #65 even if I am not sure up to which point we should check getters and setters of the model.

**Comment by StefanoSperetta** [comment]
I think it should not matter as long as the system is timezone aware. But we will have to enforce displaying in a certain time zone. You can find two main mindsets in operators: the vast majority ONLY uses UTC for everything but others prefer to always have local time for everything as you avoid confusion.

The fundamental thing is that data is saved "with time zone": for the sake of simplicity, I would always store it in UTC in the database (but I am currently not enforcing this.. it is only stored with the timezone). Probably having it in UTC in the database is simpler...

**Review by iiacoban42 — APPROVED** [review]
Okay we store UTC now for consistency. We could add an option to convert to any timezone on the website, sounds nice to have.

**Comment by StefanoSperetta** [comment]
you often see a select box or a button ti switch between local time and UTC as on n2yo (https://www.n2yo.com/satellite/?s=51074)

image

**Pull request merged**
