### PR TITLE
Grafana file config and delfi pq dashboards 

### PR DESCRIPTION
**Pull request by iiacoban42**
- Added validity based tags to the telemetry data.
- Configured grafana and influxdb from yml files
- Added a dashboard import for DelfiPQ in `grafana/dashboards/delfi_pq.json`

### CODE REVIEW

**Comment by StefanoSperetta** [comment]
Grafana now works through the reverse proxy. I also fixed the links in the homepage template but they can only work either in the development or in the deployment version... Not a great solution but I prefer keeping the deployment version working...

**Comment by StefanoSperetta** [comment]
Dummy telemetry import fails on the production server:

Traceback (most recent call last):
  File "/app/./delfipq/views.py", line 56, in add_dummy_tlm_raw_data
    stored = store_raw_frame(frame["timestamp"],
  File "/app/./delfipq/process_raw_telemetry.py", line 22, in store_raw_frame
    tlm_scraper.include_timestamp_in_scraped_tlm_range(SATELLITE, link, timestamp)
  File "/app/./transmission/telemetry_scraper.py", line 75, in include_timestamp_in_scraped_tlm_range
    update_scraped_tlm_timestamps(satellite, link, start_time, end_time)
  File "/app/./transmission/telemetry_scraper.py", line 90, in update_scraped_tlm_timestamps
    with open(SCRAPED_TLM_FILE, "w", encoding="utf-8") as file:
PermissionError: [Errno 13] Permission denied: 'transmission/scraped_telemetry.json'

**Comment by StefanoSperetta** [comment]
Manually running https://delfitlm.tudelft.nl/delfipq/process-tlm/ caused an error 504 (Timeout) making also django not available. I guess when processing starts (and there are many frames to process) this takes away CPU time from the other Django tasks. The server is still responding (SSH works fine, Grafana also works fine) so I think the scheduler processing a lot of telemetry causes some issue to the Django app...

After a while though (not sure exactly how long, I checked few hour later) the application is again working normally.

**Comment by StefanoSperetta** [comment]
Question about InfluxDB and buckets: how many should we use? 2 buckets per satellite (raw and processed data)?

I noticed the bucket is re-created every time docker restarts (https://github.com/iiacoban42/DelfiTLM/blob/50fe0f026bf096e5d7138b8829f58465b3a2c1be/docker-compose.yml#L55) and all data is actually lost when restarting docker. I am not sure if it is better to have the buckets created in code (especially to try and have them persistent) and not to hardcode in too many places how many satellites we have.

**Comment by iiacoban42** [comment]
I think we can ditch telemetry ingestion via urls entirely and use custom the Django commands from the `app-logger` branch:
- `pyhon manage.py adddelfipqdata` https://github.com/iiacoban42/DelfiTLM/blob/app-logger/src/transmission/management/commands/adddelfipqdata.py 

We can also create the buckets with them and can definitely add more for other functionality
-  `pyhon manage.py initbuckets`  https://github.com/iiacoban42/DelfiTLM/blob/app-logger/src/transmission/management/commands/initbuckets.py

**Pull request merged**
